# Generated by Django 5.0 on 2023-12-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='nothing.jpg', upload_to='Category'),
        ),
    ]
